version: 2.1
jobs:
  build:
    docker:
      - image: python:3.10

    steps:
      - checkout

      - run:
          name: Run linter
          command: ./lint.sh

      - run:
          name: Run tests
          command: python -m pytest
